### PR TITLE
feat: AsyncDevice support write_vectored asynchronously

### PR DESCRIPTION
**Pull request by zonyitoo**
ref #19
ref #38 

@meh You have released v0.5.2 too fast!!

### CODE REVIEW

**Comment by zonyitoo** [comment]
Ping @meh

**Comment by meh** [comment]
Keep pinging tomorrow if I don't publish the crate please.

**Comment by zonyitoo** [comment]
Haha. 1st Ping. @meh Please make a new release.

**Comment by zonyitoo** [comment]
Ping @meh

**Comment by zonyitoo** [comment]
Ping @meh

**Comment by zonyitoo** [comment]
Ping @meh

**Comment by zonyitoo** [comment]
Ping @meh

**Comment by meh** [comment]
It has been done!

**Pull request merged**
